plugins:
    agent_snmp:
        executor: host_agent
        source: https://github.com/geokala/cloudify_snmp_examples/archive/0.1.2.zip
        package_name: cloudify-agent-snmp-plugin
        package_version: '0.1.2'
        install: true
